# Generated by Django 3.2.18 on 2023-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creater',
            new_name='creator',
        ),
    ]
